name: flutter_um
description: "UM Hackathon 2025 Application Submission."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/bank_islam_logo.png
    - assets/orange_back.jpeg
    - assets/Graphic-T-Shirt-PNG.png
    - assets/Sneakers.png
  
  
  
  uses-material-design: true
