// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1gp39s1kev15qTq9Ex9_o2WbtmlGZpEA',
    appId: '1:224449223619:web:a2a6dbbc707c3f266a3b76',
    messagingSenderId: '224449223619',
    projectId: 'umhackathon-632d1',
    authDomain: 'umhackathon-632d1.firebaseapp.com',
    storageBucket: 'umhackathon-632d1.firebasestorage.app',
    measurementId: 'G-J4ECXBBJ16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNaeUdz9ChkiCKf_5quR-8qZy2LPISOsI',
    appId: '1:224449223619:android:a7538ea690b12be46a3b76',
    messagingSenderId: '224449223619',
    projectId: 'umhackathon-632d1',
    storageBucket: 'umhackathon-632d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-p5TYo2SljKVk12qZ9yZ2tIyWvLWoI5o',
    appId: '1:224449223619:ios:f5ca61baab3094586a3b76',
    messagingSenderId: '224449223619',
    projectId: 'umhackathon-632d1',
    storageBucket: 'umhackathon-632d1.firebasestorage.app',
    iosBundleId: 'com.example.flutterUm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-p5TYo2SljKVk12qZ9yZ2tIyWvLWoI5o',
    appId: '1:224449223619:ios:f5ca61baab3094586a3b76',
    messagingSenderId: '224449223619',
    projectId: 'umhackathon-632d1',
    storageBucket: 'umhackathon-632d1.firebasestorage.app',
    iosBundleId: 'com.example.flutterUm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1gp39s1kev15qTq9Ex9_o2WbtmlGZpEA',
    appId: '1:224449223619:web:285141f6dd4206256a3b76',
    messagingSenderId: '224449223619',
    projectId: 'umhackathon-632d1',
    authDomain: 'umhackathon-632d1.firebaseapp.com',
    storageBucket: 'umhackathon-632d1.firebasestorage.app',
    measurementId: 'G-1811BNM2W4',
  );

}